### ISSUE TITLE
Plugin 1.12 and 1.13 don't working with SQ 9.8

### ISSUE THREAD

**Issue by LocalHeroPro** [mc1arke/sonarqube-community-branch-plugin#704] opened 2022-12-19 19:24 UTC
**Describe the bug**
When we start SQ with plugin v1.13, we can't load project dashboard page.

**To Reproduce**
1. Go to project dashboard
2. See error

**Expected behavior**
We can see main page of each project.

**Screenshots**
![image](https://user-images.githubusercontent.com/42643563/208503547-98137548-bff9-43db-ae2b-384b8d5d6370.png)

**Software Versions**
 - SonarQube Version: 9.8
 - Plugin Version: 1.13

**Comment by mc1arke** [comment] 2022-12-19 20:50
There are binary incompatible changes in the API classes and dependencies of the Pull Request webservice (the network request you've captured in your screenshot) and in the scanner engine which will prevent these components working with older plugin versions. I've not been able to test for any other functionally impacting changes with my update code yet as there isn't an image of this latest Sonarqube version on Docker Hub yet.

**Comment by AHagemannCK** [comment] 2022-12-20 15:12
> **Describe the bug** When we start SQ with plugin v1.13, we can't load project dashboard page.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to project dashboard
> 2. See error
> 
> **Expected behavior** We can see main page of each project.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/42643563/208503547-98137548-bff9-43db-ae2b-384b8d5d6370.png)
> 
> **Software Versions**
> 
> * SonarQube Version: 9.8
> * Plugin Version: 1.13

I've forked and changed sonarqube to bring back the required services: https://github.com/AHagemannCK/sonarqube/commit/2dc95f2ff11217347f7dd477aa6e946a9db80759

In addition I've built the docker image: https://hub.docker.com/repository/docker/cloudkasten/sonar-with-branch
which works with the 1.13-SNAPSHOT of the plugin.

Cheers,
Alex

**Comment by OneCyrus** [comment] 2022-12-21 13:02
so they removed the API layer from SonarQube 9.8? Is this something the plugin can provide as well or do we need custom SonarQube versions from now on?

**Comment by mc1arke** [comment] 2022-12-21 16:56
> so they removed the API layer from SonarQube 9.8
Not quite. Sonarsource removed the components that are required with they way one of the services the plugin was implemented, but this is a common thing that we have to work around between Sonarqube versions. They've also removed the models and interfaces required for another service, but that's because they've also stopped using that service in this release.

> Is this something the plugin can provide as well or do we need custom SonarQube versions from now on?
The plugin will be updated to implement the services in a way that returns the data required by the published version of Sonarqube, so I wouldn't expect people to need to use custom versions of Sonarqube.

**Comment by mc1arke** [comment] 2022-12-31 15:54
Released in 1.14.0 of the plugin

**Closed by mc1arke** 2022-12-31 15:54 UTC
Labels: bug

**Comment by dodgemich** [comment] 2023-01-03 16:59
Still debugging, but has 1.14 been verified against an existing install on 9.8-community?   

Picking up the latest copy of 1.14 on 9.8 server, the app fails to boot - it kicks out during autowiring of the branch plugin, with the last logging being for the bean for WebServerExtensionInstaller via the Configuration constructor.

(The app boots successfully with the plugin removed/disabled.)

**Comment by kokarn** [comment] 2023-01-03 17:10
> Still debugging, but has 1.14 been verified against an existing install on 9.8-community?

I can confirm we upgraded to 9.8-community and version 1.14 of the plugin successfully

**Comment by LocalHeroPro** [comment] 2023-01-03 18:10
Same here, but with some 403 issues in network tab. Right now I don't bother about them, because main functionality working as expected.
