### ISSUE TITLE
Stale branches/PullRequests are not deleted after time period

### ISSUE THREAD

**Issue by mazmar** [mc1arke/sonarqube-community-branch-plugin#221] opened 2020-07-23 13:28 UTC
**Describe the bug**
After several months of using sonarqube 8.1 (now 8.3) we have numerous pull requests that are not being purged automatically.

Sonarqube sais it will delete branches older than 30days with no analysis but it doesn't

**Expected behavior**
All branches older than 30days should be removed

**Screenshots**
![Screenshot 2020-07-23 at 15 24 28](https://user-images.githubusercontent.com/597771/88291880-2e10d700-ccf9-11ea-9587-4c0b31889e5d.png)

**Software Versions**
 - SonarQube Version: 8.3.1.34397
 - Plugin Version: 1.3.2-SNAPSHOT, from sq_82 branch

**Comment by egherrmann** [comment] 2020-07-23 14:24
Related to closed issue #174

**Comment by gjabouley-invn** [comment] 2020-07-23 16:04
Same issue here, but we are also seeing the same behavior on a SonarQube Developer edition instance (without this community plugin as feature is built-in in this paid version)

https://community.sonarsource.com/t/is-it-possible-to-manually-trigger-a-dbcleaner-task

**Comment by mc1arke** [comment] 2020-07-26 13:24
@mazmar Can you confirm when any of the branches on the project you've shown were last scanned?

**Comment by css-inverso** [comment] 2020-07-27 08:26
Hi,

we had the same problem and a coworker didn't have it. The difference was that he actually changed the setting to seven days and it worked fine. After that I entered 31 days, saved and changed it back to 30. It shows up as changed in relation to the default and it deleted all the branches and PRs at the next scan of our main branch.

I had a look at the code of that property and I think the setting doesn't make it into the servers configuration if you don't change it so the cleaner does not see it.

hope that helps
Christian

**Comment by gjabouley-invn** [comment] 2020-07-30 14:44
Here is the content of the database of our Community edition.

As you can see, latest analysis on master branch was on 2020-07-13 08:05:52, so all PR analysis are older than 30 days (default configuration), but still there.

|  kee   | branch_type  |  created_at         |  updated_at         | exclude_from_purge 
|--------|--------------|---------------------|---------------------|--------------------
| 378    | PULL_REQUEST | 2020-05-18 12:29:38 | 2020-05-18 12:29:38 | f
| 370    | PULL_REQUEST | 2020-04-17 15:09:40 | 2020-04-20 09:46:53 | f
| 371    | PULL_REQUEST | 2020-04-20 12:09:17 | 2020-04-20 12:09:17 | f
| 374    | PULL_REQUEST | 2020-05-04 15:00:48 | 2020-05-05 08:55:13 | f
| 382    | PULL_REQUEST | 2020-05-26 09:05:45 | 2020-05-26 09:05:45 | f
| 377    | PULL_REQUEST | 2020-05-13 15:32:15 | 2020-05-14 08:37:52 | f
| 383    | PULL_REQUEST | 2020-05-27 10:29:52 | 2020-05-27 12:52:50 | f
| master | BRANCH       | 2020-02-13 16:34:46 | **2020-07-13 08:05:52** | t

Maybe the assumption from @css-inverso is correct, i'll try to effectively set the value to 30 instead of relying to default. If it works, maybe there is an issue with default value in the plugin code.

But since we upgraded recently to 8.4.1, all `updated_at` fields of the database have been updated to upgrade date... so we will need to wait one month before testing again

**Comment by gjabouley-invn** [comment] 2020-09-04 07:49
I can confirm that effectively setting the configuration value `sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs`
 to 30 did fix our issue.

**Comment by mc1arke** [comment] 2020-10-25 20:27
Closing this since it's an issue in Sonarqube core rather than this plugin

**Closed by mc1arke** 2020-10-25 20:27 UTC
Labels: bug, question
