### ISSUE TITLE
Project's "new code" setting is not saved

### ISSUE THREAD

**Issue by regentov** [mc1arke/sonarqube-community-branch-plugin#427] opened 2021-08-24 03:01 UTC
**Describe the bug**
The plugin no longer supports "sonar.branch.target" setting to compute the difference between "sonar.branch.name" and "sonar.branch.target" code quality.

[Docs](https://docs.sonarqube.org/8.9/project-administration/new-code-period/) suggests configuring "new code definition" globally, per-project or per-branch.

There is no way to set reference branch globally (there are only two options, "previous version" or "number of days" in global settings).

There seems to be the config in the project settings. But clicking "save" button does nothing and the setting remains unchanged.

Setting reference branch on per-branch basis is the only option that works, but setting it on every new branch cannot be automated.

**To Reproduce**
1. Go to "Project settings -> New Code", Click on "Define a specific setting for this project -> Reference branch", choose a branch.
![image](https://user-images.githubusercontent.com/26378677/130548595-c23ad440-de28-4d15-b7fe-51f81614e5e2.png)
2. Click on 'Save'
3. Go to "Project settings -> New Code" again
4. See that the option "Use the general setting" is active, so it was not saved on step 2.
![image](https://user-images.githubusercontent.com/26378677/130548650-c93c7af7-9782-4eff-930b-2aabe90a3364.png)
The change is not applied after next analysis as well.

**Expected behavior**
Project settings -> New Code -> Define a specific setting for this project -> Reference branch is saved when you click "Save".

**Software Versions**
 - SonarQube Version: Community 8.9.2 (build 46101)
 - Plugin Version: 1.8.0

**Comment by mc1arke** [comment] 2021-08-24 07:24
Duplicate of #272 ? If so, this is fixed 1.8.1 of the plugin.

**Closed by mc1arke** 2021-08-24 07:24 UTC
Labels: bug

**Comment by regentov** [comment] 2021-08-24 09:23
Yes, that was a duplicate. Problem is fixed in 1.8.1.
