### ISSUE TITLE
Sonar 9 - java.lang.IllegalStateException: The action 'create_bitbucketcloud' is defined multiple times in the web service 'api/alm_settings'

### ISSUE THREAD

**Issue by ufalak** [mc1arke/sonarqube-community-branch-plugin#405] opened 2021-08-04 15:01 UTC
After installing this plugin in Sonar 9.0.1 i get this error in the web.log file:

Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: The action 'create_bitbucketcloud' is defined multiple times in the web service 'api/alm_settings'
	at org.sonar.api.server.ws.WebService$NewController.createAction(WebService.java:176)
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.CreateAction.define(CreateAction.java:44)
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.CreateAction.define(CreateAction.java:29)
	at org.sonar.server.almsettings.ws.AlmSettingsWs.lambda$define$0(AlmSettingsWs.java:38)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.sonar.server.almsettings.ws.AlmSettingsWs.define(AlmSettingsWs.java:38)
	at org.sonar.server.ws.WebServiceEngine.start(WebServiceEngine.java:76)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:577)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:187)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mc1arke** [comment] 2021-08-05 08:22
Effectively a duplicate of #384 - the plugin does not currently support Sonarqube 9. See #388 for a proposed fix.

**Closed by mc1arke** 2021-08-05 08:22 UTC
