### ISSUE TITLE
PR decoration: For line type REMOVED the only valid file type is FROM (was: TO)

### ISSUE THREAD

**Issue by racodond** [mc1arke/sonarqube-community-branch-plugin#134] opened 2020-03-18 20:33 UTC
Hi,

One of my Bitbucket PR decorations failed with the following error message:

`2020.03.18 21:16:50 INFO  ce[AXDvSpwAOt-M153AClS0][c.g.m.s.p.c.p.b.s.BitbucketServerPullRequestDecorator] starting to analyze with com.github.mc1arke.sonarqube.plugin.ce.pullrequest.AnalysisDetails@41982f12
2020.03.18 21:16:50 ERROR ce[AXDvSpwAOt-M153AClS0][c.g.m.s.p.c.p.b.s.BitbucketServerPullRequestDecorator] {"errors":[{"context":null,"message":"For line type REMOVED the only valid file type is FROM (was: TO)","exceptionName":"com.atlassian.bitbucket.validation.ArgumentValidationException"}]}`

Here's the diff of the PR:
![image](https://user-images.githubusercontent.com/1215713/77004749-ec91a900-695f-11ea-9a34-2ad96e674664.png)

I'm running SonarQube 7.9.2 and version 1.3.0 of the plugin.

Thank you

Regards,

David

**Comment by 4n4n4s** [comment] 2020-03-22 16:16
Hi @racodond are you sure that the change in this file causes the issue? Cause it says line type "REMOVED" and this looks only like a change. 

Can you isolate it and only start a review with this change?

If the issue is still occuring I'll check the logic and push a fix for it. Thank you.

**Comment by racodond** [comment] 2020-03-25 15:24
Hi @4n4n4s,

I confirm the issue. I just create a project with one single file (see html code below).

![image](https://user-images.githubusercontent.com/1215713/77553097-a767fc80-6eb4-11ea-8ac6-5988392780ec.png)

It doesn't seem to be just a change. It's line removal + line addition (both of them marked as line #12).

`
<div class="todo-content">
    <h1 class="page-title">My Todos</h1>
    <div class="todo-create">
        <form #todoForm="ngForm" (ngSubmit) = "createTodo(todoForm)" novalidate>
            <input type="text" id="title" class="form-control" placeholder="Type a todo and press enter..."
                   required
                   name="title" [(ngModel)]="newTodo.title"
                   #title="ngModel" >
            <div *ngIf="title.errors && title.dirty"
                 class="alert alert-danger">
                <div [hidden]="!title.errors.required">
                    Title is required.
                </div>
            </div>
        </form>
    </div>
</div>
`

Thanks!

David

**Comment by 4n4n4s** [comment] 2020-03-30 17:30
Indeed it's "REMOVED" and "ADDED" at the same time. Will push a fix that we ignore the "REMOVED" ones for now.

**Comment by racodond** [comment] 2020-03-31 17:38
Cool! Thanks!

**Comment by mc1arke** [comment] 2020-06-07 15:01
Closing this since we've switched to using Bitbucket Code Insights so have re-written all this code. Please re-open if you can replicate this with a newer version of the plugin

**Closed by mc1arke** 2020-06-07 15:01 UTC
