### ISSUE TITLE
GitHub checkRun fails when lots of annotations exists in the mutation

### ISSUE THREAD

**Issue by tuomoa** [mc1arke/sonarqube-community-branch-plugin#159] opened 2020-04-21 11:57 UTC
**Describe the bug**
Plugin fails silently to decorate GitHub PR when there are lots of annotations (https://developer.github.com/v4/input_object/checkrunoutput/) in the `createCheckRun` mutation. When creation is successful, GitHub responses
```
HTTP/1.1 200 OK
{
  "data": {
    "createCheckRun": {
      "clientMutationId": null,
      "checkRun": {
        "id": "<.....id here ...>"
      }
    }
  }
}
```
but when it does not work:
```
HTTP/1.1 200 OK
{
  "data": {
    "createCheckRun": {
      "clientMutationId": null,
      "checkRun": null
    }
  }
}
```

I think the count of annotation elements is limited to 50:
> Adds information from your analysis to specific lines of code. Annotations are visible on GitHub in the Checks and Files changed tab of the pull request. The Checks API limits the number of annotations to a maximum of 50 per API request. To create more than 50 annotations, you have to make multiple requests to the Update a check run endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. For details about how you can view annotations on GitHub, see "About status checks". See the annotations object description for details about how to use this parameter.
(https://developer.github.com/v3/checks/runs/)

I also tested this with curl by posting the same request to the GraphQL endpoint and when I posted exactly 50 or less annotation elements it worked. If there were more elements it failed to create the check run.

Also when this happens the plugin does not log any kind of errors. Maybe it should log an error if the GraphQL endpoints response does not contain checkRun id?

**To Reproduce**
1. Analyze project with >50 problems that appear on annotations and try to use PR decoration
2. Check log for no failures
3. Check GitHub and see that no checkRun apperas

**Expected behavior**
Decoration works as it should. There should be error in the log if decoration failed.

**Screenshots**
N/A

**Software Versions**
 - SonarQube Version: 7.9 LTS
 - Plugin Version: Snapshot with base version 1.3.0 and cherrypicked fix #103 

**Additional context**
N/A

**Comment by mc1arke** [comment] 2020-04-24 14:35
Thanks for your report. #154 reports the same issue so I'm closing this as a duplicate of that report.

**Closed by mc1arke** 2020-04-24 14:35 UTC
Labels: bug
