### ISSUE TITLE
sonarqube 7.4 branch 

### ISSUE THREAD

**Issue by imex163** [mc1arke/sonarqube-community-branch-plugin#11] opened 2019-05-07 08:20 UTC
Hello,

I'm using Sonarqube 7.4 in docker(official image) with an extended folder with extensions  
If I'm running like this

```
bat "D:\\sonar-scanner-msbuild\\SonarQube.Scanner.MSBuild.exe begin /k:project /d:sonar.host.url=http://192.168.100.10:9000 /d:sonar.login=token"
bat "\"${MSBUILD}\" main\\project.sln"
 bat "D:\\sonar-scanner-msbuild\\SonarQube.Scanner.MSBuild.exe end /d:sonar.login=token"
```
All works, but if I added /d:sonar.branch.name=test - I've got an error:
```
bat "D:\\sonar-scanner-msbuild\\SonarQube.Scanner.MSBuild.exe begin /k:project/d:sonar.host.url=http://192.168.100.10:9000 /d:sonar.branch.name=test /d:sonar.login=token"
bat "\"${MSBUILD}\" main\\project.sln"
bat "D:\\sonar-scanner-msbuild\\SonarQube.Scanner.MSBuild.exe end /d:sonar.login=token"
```

```
[ERROR: Error during SonarQube Scanner execution
ERROR: Unable to load component class org.sonar.scanner.phases.AbstractPhaseExecutor
ERROR: Caused by: Unable to load component class org.sonar.scanner.phases.PostJobsExecutor
ERROR: Caused by: Unable to load component class org.sonar.scanner.bootstrap.ScannerExtensionDictionnary
ERROR: Caused by: Unable to load component class org.sonar.scanner.sensor.DefaultSensorContext
ERROR: Caused by: Unable to load component class org.sonar.scanner.scan.filesystem.DefaultModuleFileSystem
ERROR: Caused by: Unable to load component class org.sonar.scanner.scan.filesystem.StatusDetection
ERROR: 
The SonarQube Scanner did not complete successfully]
```

While SQ is running, I have warnings:
```
2019.05.06 18:56:11 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
2019.05.06 18:56:13 WARN  ce[][o.s.c.p.ComponentKeys] Bad component key: org.sonar.java.externalreport.ExternalRulesDefinition@11d7a390. Please implement toString() method on class org.sonar.java.externalreport.ExternalRulesDefinition
2019.05.06 18:56:13 WARN  ce[][o.s.c.p.ComponentKeys] Bad component key: org.sonar.java.externalreport.ExternalRulesDefinition@4429ab31. Please implement toString() method on class org.sonar.java.externalreport.ExternalRulesDefinition
2019.05.06 18:56:13 WARN  ce[][o.s.c.p.ComponentKeys] Bad component key: org.sonar.java.externalreport.ExternalRulesDefinition@7e3d1fb2. Please implement toString() method on class org.sonar.java.externalreport.ExternalRulesDefinition
```
Could you help me, what am I doing wrong?
P.S. I'm using plugin version 1.0.2
P.S.S. analyses from master branch exists

**Comment by mc1arke** [comment] 2019-05-07 09:38
Could you add `/d:sonar.verbose=true` to the `begin` line so the scanner engine gives some more detailed logging around the failure and any execution values?

**Comment by imex163** [comment] 2019-05-07 11:14
Yes, I have uploaded log to:
https://0bin.net/paste/f8L9xf4UszUc86nZ#YwQVZil6OlgPafhqLK752Xy17REYaXLBq8aVsnYqPvU

**Comment by mc1arke** [comment] 2019-05-07 11:28
Can you confirm that your working directory is a Git directory? You're getting a `NullPointerException` from JGit whilst SonarQube is attempting to gather blame information for changed files.

**Comment by imex163** [comment] 2019-05-07 11:42
Yes, I think, because before analyze I'm getting checkout...

**Comment by mc1arke** [comment] 2019-05-07 12:02
Are you doing this as part of a CI build solution (e.g. Jenkins) or running this locally? What command is being run for the checkout, and what does `git status` show before the SonarQube analysis runs?

**Comment by imex163** [comment] 2019-05-07 12:50
`Are you doing this as part of a CI build solution (e.g. Jenkins) or running this locally?`
I'm doing it as part of a CI build solution.

```
[Pipeline] { (SCM)
[Pipeline] checkout
using credential cred_id
Fetching changes from the remote Git repository
 > git rev-parse --is-inside-work-tree # timeout=10
 > git config remote.project.url git_url # timeout=10
Fetching upstream changes from git_url
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress git_url +refs/heads/*:refs/remotes/project/*
Checking out Revision revision (refs/remotes/project/master)
 > git rev-parse "refs/remotes/project/master^{commit}" # timeout=10
 > git rev-parse "refs/remotes/project/project/master^{commit}" # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f sha # timeout=20
Commit message: "gitignore"
 > git rev-list --no-walk sha # timeout=10
[Pipeline] }
```
git status:
```
+ git status
HEAD detached at 4bfca0758
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.sonarqube/
	TestResult.xml
	main/project/Conf/ConnectionString - Copy.config

nothing added to commit but untracked files present (use "git add" to track)
[Pipeline] bat

D:\Jenkins\workspace\test-brunch>D:\sonar-scanner-msbuild\SonarQube.Scanner.MSBuild.exe begin /k:project /d:sonar.host.url=http://192.168.100.10:9000 /d:sonar.verbose=true /d:sonar.branch.name=test /d:sonar.login=login /d:sonar.css.node=D:\Jenkins\nodejs\node 
```

**Comment by imex163** [comment] 2019-05-07 13:08
I've found some interesting thing:
```
17:06:02.422 INFO: SCM collecting changed files in the branch
17:06:02.441 DEBUG: readpipe [git, --version],C:\Program Files\Git\cmd
17:06:03.027 DEBUG: readpipe may return 'git version 2.21.0.windows.1'
17:06:03.027 DEBUG: remaining output:

17:06:03.037 DEBUG: readpipe [git, config, --system, --edit],C:\Program Files\Git\cmd
17:06:03.370 DEBUG: readpipe may return 'C:/Program Files/Git/mingw64/etc/gitconfig'
17:06:03.371 DEBUG: remaining output:

17:06:04.027 INFO: ------------------------------------------------------------------------
17:06:04.027 INFO: EXECUTION FAILURE
```
Could it be related?

**Comment by mc1arke** [comment] 2019-05-07 14:15
I suspect you're being hit by https://community.sonarsource.com/t/npe-when-scanning-a-merge-branch-in-jenkins/5168. I don't know if it's the Sparse Checkout or the Detached Checkout that's causing you problems, but potentially running `git checkout __branchname__` (where `__branchname__` is the branch you're trying to build) manually after the Jenkins checkout but before your scan may resolve your problem for now.

**Comment by imex163** [comment] 2019-05-08 05:33
I've tried it, but I'm getting the same errors(
```
[Pipeline] sh
+ git status
HEAD detached at 4bfca0758
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.sonarqube/
	TestResult.xml
	main/project/Conf/ConnectionString - Copy.config

nothing added to commit but untracked files present (use "git add" to track)
[Pipeline] sh
+ git checkout branch_name
Switched to branch 'branch_name'
[Pipeline] sh
+ git rev-parse HEAD
4bfca07587a593036951405b241dc179d97defc1
[Pipeline] bat

D:\Jenkins\workspace\test-brunch>D:\sonar-scanner-msbuild\SonarQube.Scanner.MSBuild.exe begin /k:zetta /d:sonar.host.url=http://192.168.100.10:9000 /d:sonar.verbose=true /d:sonar.branch.name=test /d:sonar.login=login /d:sonar.css.node=D:\Jenkins\nodejs\node  
```
Thank you

**Comment by mc1arke** [comment] 2019-05-09 12:52
Does the build/scan work if you clone the repository without using Jenkins? Jenkins is still setting `git config core.sparsecheckout` on the checked-out repo which may be causing you issues.

I'm tempted to close this issues as Invalid given it's an issue internal to SonarQube and not caused by this plugin (the branch plugin is just allowing you to find the issue), but I'm happy to help try and get to the bottom of the problem.

**Comment by mc1arke** [comment] 2019-05-13 07:28
Closing issues since no further update provided and the root cause does not seem to relate to this plugin.

**Closed by mc1arke** 2019-05-13 07:28 UTC
Labels: question
