### ISSUE TITLE
plugin does not submit PR status Azure

### ISSUE THREAD

**Issue by narkonst** [mc1arke/sonarqube-community-branch-plugin#503] opened 2021-11-30 10:56 UTC
**Describe the bug**
Plugin does not submit PR status Azure

**Software Versions**
 - SonarQube Version: 8.9.3.48735
 - Plugin Version: 1.8.1

**Additional context**
ce.log
`2021.11.30 13:11:02 INFO  ce[AX1vroc4_LFg4jSRZHma][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] using pull request decorator com.github.mc1arke.sonarqube.plugin.ce.pullrequest.azuredevops.AzureDevOpsPullRequestDecorator

2021.11.30 13:11:03 ERROR ce[AX1vroc4_LFg4jSRZHma][c.g.m.s.p.c.p.a.AzureDevopsRestClient] Azure Devops response status did not match expected value. Expected: 200\r\nHTTP/1.1 400 Bad Request\r\n{"$id":"1","innerException":null,"message":"The requested version \"4.1\" of the resource is under preview. The -preview flag must be supplied in the api-version for such requests. For example: \"4.1-preview\"","typeName":"Microsoft.VisualStudio.Services.WebApi.VssInvalidPreviewVersionException, Microsoft.VisualStudio.Services.WebApi","typeKey":"VssInvalidPreviewVersionException","errorCode":0,"eventId":3000}

2021.11.30 13:11:03 ERROR ce[AX1vroc4_LFg4jSRZHma][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalStateException: An unexpected response code was returned from the Azure Devops API - Expected: 200, Got: 400 at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.azuredevops.AzureDevopsRestClient.validateResponse(AzureDevopsRestClient.java:157)`

**Comment by mc1arke** [comment] 2021-12-14 09:27
Duplicate of  #442

**Closed by mc1arke** 2021-12-14 09:27 UTC
Labels: bug, duplicate
