### ISSUE TITLE
Sonarqube 7.9 branches not working

### ISSUE THREAD

**Issue by amonea** [mc1arke/sonarqube-community-branch-plugin#23] opened 2019-07-01 15:45 UTC
**Describe the bug**
Plugin does not work with the recently released Sonarqube 7.9

**To Reproduce**
Analyze a project against a Sonarqube 7.9 server with plugin version 1.1.1 installed. 

**Expected behavior**
Analysis succeeds.

**Scanner Output**
The following can be seen in the output: 

```ERROR: Error during SonarQube Scanner execution
ERROR: Unable to load component class org.sonar.scanner.scan.filesystem.InputComponentStore
ERROR: Caused by: Unable to load component interface org.sonar.scanner.scan.branch.BranchConfiguration
ERROR: Caused by: Receiver class com.github.mc1arke.sonarqube.plugin.scanner.CommunityBranchConfigurationLoader does not define or inherit an implementation of the resolved method abstract load(Ljava/util/Map;Lorg/sonar/scanner/scan/branch/ProjectBranches;Lorg/sonar/scanner/scan/branch/ProjectPullRequests;)Lorg/sonar/scanner/scan/branch/BranchConfiguration; of interface org.sonar.scanner.scan.branch.BranchConfigurationLoader.
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

**Software Versions**
 - SonarQube Version: 7.9
 - Plugin Version: 1.1.1

**Additional context**
Project analysis works with SQ 7.8 and same plugin version 1.1.1. Upgrade to 7.9 shows this, most likely the Sonarqube branch API changed again.

**Comment by mc1arke** [comment] 2019-07-01 15:50
Thanks for the report. I'd created the [feature/sq-7_9-support](https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/feature/sq-7_9-support) branch which contains changes necessary to run against SonarQube's 7.9-SNAPSHOT up until any changes they may have made this morning. I'll re-test it against the full 7.9 release shortly and perform a release if I don't encounter any significant issues. Feel free to build and test this branch yourself and provide any feedback in the meantime.

**Comment by amonea** [comment] 2019-07-01 17:57
Will build myself in the next 2 hrs and report back, thank you.

**Comment by amonea** [comment] 2019-07-01 18:29
I have built from the branch you indicated and installed the new artifact; very happy to report everything is working again with SQ 7.9! If you make any more changes I'd love to help test the final version before you release it. Thank you!

**Comment by mc1arke** [comment] 2019-07-01 19:18
Thanks for the confirmation. I've raised #24 with cleaned-up versions of my previous commits. It runs successfully against the 7.9 release, so I'm just going to give it a quick regression against 7.8, then I'll merge it and create a release.

**Comment by mc1arke** [comment] 2019-07-01 20:15
Updates merged and released under [version 1.1.1](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.1.1).

**Closed by mc1arke** 2019-07-01 20:15 UTC
Labels: bug

**Comment by danbao** [comment] 2019-07-10 04:08
```bash
[root@xia01-i01-dck02 dck02]# docker logs sonarqube -f
2019.07.10 04:05:20 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.07.10 04:05:20 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.07.10 04:05:21 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2019.07.10 04:05:21 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.07.10 04:05:21 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.07.10 04:05:21 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[thread 260 also had an error][thread 257 also had an error]

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fe9a46461b7, pid=32, tid=258
#
# JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+7, mixed mode, tiered, compressed oops, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# J 5105 c2 com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.calcHash([II)I (115 bytes) @ 0x00007fe9a46461b7 [0x00007fe9a46460a0+0x0000000000000117]
#
# Core dump will be written. Default location: /opt/sonarqube/elasticsearch/core.32
#
# An error report file with more information is saved as:
# ../logs/es_hs_err_pid32.log
[thread 252 also had an error][thread 250 also had an error][thread 261 also had an error]


Compiled method (c1)   16040 4685       3       sun.nio.ch.Util::offerFirstTemporaryDirectBuffer (53 bytes)
 total in heap  [0x00007fe99d1b0590,0x00007fe99d1b1468] = 3800
 relocation     [0x00007fe99d1b0708,0x00007fe99d1b07f0] = 232
 main code      [0x00007fe99d1b0800,0x00007fe99d1b10e0] = 2272
 stub code      [0x00007fe99d1b10e0,0x00007fe99d1b11d8] = 248
 metadata       [0x00007fe99d1b11d8,0x00007fe99d1b1210] = 56
 scopes data    [0x00007fe99d1b1210,0x00007fe99d1b12b0] = 160
 scopes pcs     [0x00007fe99d1b12b0,0x00007fe99d1b1420] = 368
 dependencies   [0x00007fe99d1b1420,0x00007fe99d1b1428] = 8
 nul chk table  [0x00007fe99d1b1428,0x00007fe99d1b1468] = 64
Compiled method (c1)   16040 4532       3       java.nio.channels.spi.AbstractInterruptibleChannel::begin (48 bytes)
 total in heap  [0x00007fe99d153e10,0x00007fe99d154bc8] = 3512
 relocation     [0x00007fe99d153f88,0x00007fe99d154030] = 168
 main code      [0x00007fe99d154040,0x00007fe99d154840] = 2048
 stub code      [0x00007fe99d154840,0x00007fe99d1548f8] = 184
 metadata       [0x00007fe99d1548f8,0x00007fe99d154948] = 80
 scopes data    [0x00007fe99d154948,0x00007fe99d154a50] = 264
 scopes pcs     [0x00007fe99d154a50,0x00007fe99d154b90] = 320
 dependencies   [0x00007fe99d154b90,0x00007fe99d154b98] = 8
 nul chk table  [0x00007fe99d154b98,0x00007fe99d154bc8] = 48
Compiled method (c1)   16041 3987       3       com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer::findName (198 bytes)
 total in heap  [0x00007fe99d9c1910,0x00007fe99d9c2840] = 3888
 relocation     [0x00007fe99d9c1a88,0x00007fe99d9c1b70] = 232
 main code      [0x00007fe99d9c1b80,0x00007fe99d9c2340] = 1984
 stub code      [0x00007fe99d9c2340,0x00007fe99d9c2448] = 264
 oops           [0x00007fe99d9c2448,0x00007fe99d9c2450] = 8
 metadata       [0x00007fe99d9c2450,0x00007fe99d9c2460] = 16
 scopes data    [0x00007fe99d9c2460,0x00007fe99d9c2580] = 288
 scopes pcs     [0x00007fe99d9c2580,0x00007fe99d9c27d0] = 592
 dependencies   [0x00007fe99d9c27d0,0x00007fe99d9c27d8] = 8
 nul chk table  [0x00007fe99d9c27d8,0x00007fe99d9c2840] = 104
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
2019.07.10 04:05:39 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 134
2019.07.10 04:05:39 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2019.07.10 04:05:39 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2019.07.10 04:05:43 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.07.10 04:05:43 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.07.10 04:05:43 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2019.07.10 04:05:43 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.07.10 04:05:44 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.07.10 04:05:44 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f0dd85ab537, pid=30, tid=210
#
# JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+7, mixed mode, tiered, compressed oops, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# J 5030 c2 com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.calcHash([II)I (115 bytes) @ 0x00007f0dd85ab537 [0x00007f0dd85ab420+0x0000000000000117]
#
# Core dump will be written. Default location: /opt/sonarqube/elasticsearch/core.30
#
# An error report file with more information is saved as:
# ../logs/es_hs_err_pid30.log
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
2019.07.10 04:06:03 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 134
2019.07.10 04:06:03 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2019.07.10 04:06:03 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2019.07.10 04:06:03 ERROR app[][o.s.a.p.EsManagedProcess] Failed to check status
java.lang.IllegalStateException: Future got interrupted
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:60)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:34)
	at org.sonar.application.es.EsConnectorImpl.getClusterHealthStatus(EsConnectorImpl.java:63)
	at org.sonar.application.process.EsManagedProcess.checkStatus(EsManagedProcess.java:88)
	at org.sonar.application.process.EsManagedProcess.checkOperational(EsManagedProcess.java:80)
	at org.sonar.application.process.EsManagedProcess.isOperational(EsManagedProcess.java:58)
	at org.sonar.application.process.ManagedProcessHandler.refreshState(ManagedProcessHandler.java:201)
	at org.sonar.application.process.ManagedProcessHandler$EventWatcher.run(ManagedProcessHandler.java:258)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:251)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:94)
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:57)
	... 7 common frames omitted
2019.07.10 04:06:08 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.07.10 04:06:08 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.07.10 04:06:08 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2019.07.10 04:06:08 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.07.10 04:06:08 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.07.10 04:06:08 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007ff203c22537, pid=32, tid=263
#
# JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+7, mixed mode, tiered, compressed oops, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# J 5100 c2 com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.calcHash([II)I (115 bytes) @ 0x00007ff203c22537 [0x00007ff203c22420+0x0000000000000117]
#
# Core dump will be written. Default location: /opt/sonarqube/elasticsearch/core.32
#
# An error report file with more information is saved as:
# /opt/sonarqube/elasticsearch/hs_err_pid32.log
[thread 258 also had an error]
[thread 261 also had an error]
[thread 260 also had an error]
[thread 259 also had an error]
[thread 264 also had an error][thread 262 also had an error]

[thread 255 also had an error]
[thread 257 also had an error][thread 254 also had an error]

Compiled method (c2)   18475 5100       4       com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer::calcHash (115 bytes)
 total in heap  [0x00007ff203c22290,0x00007ff203c22708] = 1144
 relocation     [0x00007ff203c22408,0x00007ff203c22420] = 24
 main code      [0x00007ff203c22420,0x00007ff203c22600] = 480
 stub code      [0x00007ff203c22600,0x00007ff203c22618] = 24
 oops           [0x00007ff203c22618,0x00007ff203c22620] = 8
 metadata       [0x00007ff203c22620,0x00007ff203c22628] = 8
 scopes data    [0x00007ff203c22628,0x00007ff203c22690] = 104
 scopes pcs     [0x00007ff203c22690,0x00007ff203c226f0] = 96
 dependencies   [0x00007ff203c226f0,0x00007ff203c226f8] = 8
 nul chk table  [0x00007ff203c226f8,0x00007ff203c22708] = 16
Compiled method (c2)   18480 5100       4       com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer::calcHash (115 bytes)
 total in heap  [0x00007ff203c22290,0x00007ff203c22708] = 1144
 relocation     [0x00007ff203c22408,0x00007ff203c22420] = 24
 main code      [0x00007ff203c22420,0x00007ff203c22600] = 480
 stub code      [0x00007ff203c22600,0x00007ff203c22618] = 24
 oops           [0x00007ff203c22618,0x00007ff203c22620] = 8
 metadata       [0x00007ff203c22620,0x00007ff203c22628] = 8
 scopes data    [0x00007ff203c22628,0x00007ff203c22690] = 104
 scopes pcs     [0x00007ff203c22690,0x00007ff203c226f0] = 96
 dependencies   [0x00007ff203c226f0,0x00007ff203c226f8] = 8
 nul chk table  [0x00007ff203c226f8,0x00007ff203c22708] = 16
Compiled method (c1)   18485 4014       3       com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer::findName (198 bytes)
 total in heap  [0x00007ff1fcf97790,0x00007ff1fcf986c0] = 3888
 relocation     [0x00007ff1fcf97908,0x00007ff1fcf979f0] = 232
 main code      [0x00007ff1fcf97a00,0x00007ff1fcf981c0] = 1984
 stub code      [0x00007ff1fcf981c0,0x00007ff1fcf982c8] = 264
 oops           [0x00007ff1fcf982c8,0x00007ff1fcf982d0] = 8
 metadata       [0x00007ff1fcf982d0,0x00007ff1fcf982e0] = 16
 scopes data    [0x00007ff1fcf982e0,0x00007ff1fcf98400] = 288
 scopes pcs     [0x00007ff1fcf98400,0x00007ff1fcf98650] = 592
 dependencies   [0x00007ff1fcf98650,0x00007ff1fcf98658] = 8
 nul chk table  [0x00007ff1fcf98658,0x00007ff1fcf986c0] = 104
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
2019.07.10 04:06:29 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 134
2019.07.10 04:06:29 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2019.07.10 04:06:29 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```
will failed when start from docker

**Comment by mc1arke** [comment] 2019-07-10 06:44
This looks like a failure in ElasticSearch, which the branch plugin doesn't touch. Why do you believe this is caused by the branch plugin, and why have you reported this under a resolved and seemingly unrelated issue?

**Comment by danbao** [comment] 2019-07-10 07:28
Hi @mc1arke
because I start the sonarqube without any plugins and it start success.
and then I add the [lastest plugin ](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.1.1) into /opt/sonarqube/extensions and it will report above error.

here is my docker-compose.yml
```yml
version: "3"

services:
  sonarqube:
    image: sonarqube:7.9-community
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
    restart: unless-stopped
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    networks:
      - sonar-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube_db:
    image: postgres
    container_name: sonarqube_db
    restart: unless-stopped
    networks:
      - sonar-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonar-net:
    external: true

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
```

**Comment by danbao** [comment] 2019-07-10 08:01
Hi @mc1arke my fault~ seems not cause by this plugin, I add it before start and It success. can close it ticket. I will report a bug to SonarSource/docker-sonarqube, thanks.
