### ISSUE TITLE
[QUESTION] Any experience with 10.5 yet?

### ISSUE THREAD

**Issue by OneCyrus** [mc1arke/sonarqube-community-branch-plugin#900] opened 2024-04-19 06:25 UTC
now that 10.5 is out.

https://www.sonarsource.com/products/sonarqube/whats-new/sonarqube-10-5/

anyone tried the current plugin with 10.5 yet? did it work?

**Comment by mc1arke** [comment] 2024-04-19 07:40
I've not tested the plugin against 10.5 yet. The release is binary compatible with 10.4 for the classes we depend on so the plugin compiles and starts with the UI showing branches, but I've not tried running any scans yet.

**Comment by OneCyrus** [comment] 2024-04-19 08:08
just saw this on the upgrade notes for 10.5. not sure if this has any impact on this plugin.

![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/7747800/773a7bf8-9181-4d2e-b2ac-b9e71c01554b)

https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/release-upgrade-notes/

**Comment by xC0dex** [comment] 2024-04-23 07:12
Hey, I've tested SonarQube Community Edition 10.5 with the plugin 1.19. The MR-Analysis + decoration in GitLab works fine!

**Comment by OneCyrus** [comment] 2024-04-24 20:36
we upgraded now and so far everything seems to work as expected

**Comment by dkeitzel** [comment] 2024-04-24 21:16
I ran into an incompatiblity when setting up a the 'DevOps Platform Integration' on a newly created SonarQube project. This is the exception:
```
java.lang.NoSuchMethodError: 'void org.sonar.db.alm.setting.ProjectAlmSettingDao.insertOrUpdate(org.sonar.db.DbSession, org.sonar.db.alm.setting.ProjectAlmSettingDto, java.lang.String, java.lang.String, java.lang.String)'
```
<details>

<summary>Full stacktrace</summary>

```
2024.04.24 22:45:15 ERROR web[][o.s.s.p.w.RootFilter] Processing of request /api/alm_settings/set_bitbucket_binding failed
javax.servlet.ServletException: 'void org.sonar.db.alm.setting.ProjectAlmSettingDao.insertOrUpdate(org.sonar.db.DbSession, org.sonar.db.alm.setting.ProjectAlmSettingDto, java.lang.String, ja
va.lang.String, java.lang.String)'
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:273)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:83)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:70)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.CrossOriginFilter.doFilter(CrossOriginFilter.java:51)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.CspFilter.doFilter(CspFilter.java:63)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:60)
        at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:47)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:56)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.EndpointPathFilter.doFilter(EndpointPathFilter.java:47)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:65)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:115)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:138)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:137)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:267)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1786)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'void org.sonar.db.alm.setting.ProjectAlmSettingDao.insertOrUpdate(org.sonar.db.DbSession, org.sonar.db.alm.setting.ProjectAlmSettingDto, java.lang.String, java.lang.String, java.lang.String)'
        at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.binding.action.SetBindingAction.handleProjectRequest(SetBindingAction.java:58)
        at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.binding.action.ProjectWsAction.handle(ProjectWsAction.java:73)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:114)
        at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
        at org.sonar.server.platform.web.MasterServletFilter$JavaxFilterAdapter.doFilter(MasterServletFilter.java:227)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:198)
        at org.sonar.server.platform.web.MasterServletFilter$HttpFilterChainAdapter.doFilter(MasterServletFilter.java:241)
        at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
        at org.sonar.server.platform.web.MasterServletFilter$JavaxFilterAdapter.doFilter(MasterServletFilter.java:227)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:198)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:146)
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        ... 154 common frames omitted
```
</details>

I guess the cause is commit [99bf48a](https://github.com/SonarSource/sonarqube/commit/99bf48a4107238ade798c32b9a0e17b196d16c90#diff-3081029d09c0a8ac2a5a1ac358813bcb9b7949bd9308824510edafbc4c327209R50) for `ProjectAlmSettingDao#insertOrUpdate` which is called in https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/33536122338e505088080c4795bb8b4be37588ba/src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/binding/action/SetBindingAction.java#L58

However, I just recompiled the 1.19.0 tag of this plugin but referenced sonarqube 10.5 in https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/33536122338e505088080c4795bb8b4be37588ba/build.gradle#L43

This solved the issue.

**Comment by gjabouley-invn** [comment] 2024-05-02 15:36
> we upgraded now and so far everything seems to work as expected. we are using GitHub only.

Hi, are you using 'DevOps Platform Integration' feature ?

Need to upgrade to 10.5 to fix https://sonarsource.atlassian.net/browse/SONAR-21600, but as we are heavily relying on this feature (which is not easy to test on a sandbox platform) i would prefer to confirm this point...

**Comment by RoboNET** [comment] 2024-05-06 12:18
> To be honest, I'm not sure if this header was added by SonarQube or by our host. Maybe someone else can verify this change.

I tested this on our installation. Same behavior. Looks like SonarQube started adding this headers.

**Comment by gjabouley-invn** [comment] 2024-05-06 12:40
> > To be honest, I'm not sure if this header was added by SonarQube or by our host. Maybe someone else can verify this change.
> 
> I tested this on our installation. Same behavior. Looks like SonarQube started adding this headers.

Might be related to https://sonarsource.atlassian.net/browse/SONAR-21780

Can probably we solved using https://github.com/mc1arke/sonarqube-community-branch-plugin?tab=readme-ov-file#serving-images-for-pr-decoration

**Comment by xC0dex** [comment] 2024-05-06 12:48
> Might be related to https://sonarsource.atlassian.net/browse/SONAR-21780

Good spot. Maybe they will address this issue with https://sonarsource.atlassian.net/browse/SONAR-22149

**Comment by dm-bil** [comment] 2024-05-10 13:06
Hi
Everything works fine for me except PR merge prevention
When my PR does not pass Quality Gate merge is being blocked, but when the check is passed the second check (which blocks merge or allows to merge) is in "Expected — Waiting for status to be reported" status for ages, tried to wait up to 30 mins but it was still running
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/169234956/d01a87ed-c48d-4e67-8540-a1585039dda0)

**Comment by chriscarpenter12** [comment] 2024-05-14 19:23
> I ran into an incompatiblity when setting up a the 'DevOps Platform Integration' on a newly created SonarQube project. This is the exception:
> 
> ```
> java.lang.NoSuchMethodError: 'void org.sonar.db.alm.setting.ProjectAlmSettingDao.insertOrUpdate(org.sonar.db.DbSession, org.sonar.db.alm.setting.ProjectAlmSettingDto, java.lang.String, java.lang.String, java.lang.String)'
> ```

Had the same error with 10.5 helm install with the 1.19.0 plugin. It wasn't until I added a new project that I realized it couldn't be linked in the DevOps Platform Integration settings.

**Comment by RoboNET** [comment] 2024-06-18 07:56
> > I ran into an incompatiblity when setting up a the 'DevOps Platform Integration' on a newly created SonarQube project. This is the exception:
> > ```
> > java.lang.NoSuchMethodError: 'void org.sonar.db.alm.setting.ProjectAlmSettingDao.insertOrUpdate(org.sonar.db.DbSession, org.sonar.db.alm.setting.ProjectAlmSettingDto, java.lang.String, java.lang.String, java.lang.String)'
> > ```
> 
> Had the same error with 10.5 helm install with the 1.19.0 plugin. It wasn't until I added a new project that I realized it couldn't be linked in the DevOps Platform Integration settings.

Same error. Falling when trying update settings on existing project.

**Comment by gjabouley-invn** [comment] 2024-06-20 07:54
For people having similar issue, can you test version available in https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/904#issuecomment-2129128434 and provide feedback?

**Comment by azun-c** [comment] 2024-07-16 04:17
I'm having the issue: `java.lang.NoClassDefFoundError` with SonarQube v10.5.1 and `community-branch-plugin` v1.19.0

```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:145)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:424)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
	at ch.qos.logback.classic.Logger.error(Logger.java:543)
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:87)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at org.sonarsource.scanner.api.internal.IsolatedClassloader.loadClass(IsolatedClassloader.java:82)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

and

```
04:02:17.935 ERROR: Cleanup during JVM shutdown failed
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:605)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:82)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NoClassDefFoundError: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	... 3 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jgit/internal/JGitText
	at org.eclipse.jgit.internal.util.ShutdownHook.notify(ShutdownHook.java:97)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at org.eclipse.jgit.internal.util.ShutdownHook.doCleanup(ShutdownHook.java:93)
	at org.eclipse.jgit.internal.util.ShutdownHook.lambda$1(ShutdownHook.java:80)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.internal.JGitText
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at org.sonarsource.scanner.api.internal.IsolatedClassloader.loadClass(IsolatedClassloader.java:82)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 21 common frames omitted
```

Per my investigations, i think the problem is related to: [jgit](https://github.com/eclipse-jgit/jgit/issues/36)

PS: Although there have been some errors, but still the PR decoration still works fine.

**Comment by gjabouley-invn** [comment] 2024-07-16 08:15
Hello @azun-c 

`logback` error is a cosmetic bug in 10.5, fixed in 10.6: https://community.sonarsource.com/t/error-after-analysis-noclassdeffounderror-ch-qos-logback-classic-spi-throwableproxy/113733/92
Analysis should complete anyway

For the `JGitText` error, someone mentioned in it above [discussion](https://community.sonarsource.com/t/error-after-analysis-noclassdeffounderror-ch-qos-logback-classic-spi-throwableproxy/113733/91), but not sure about the status. Seems you might need to update your Sonar Scanner...

**Comment by azun-c** [comment] 2024-07-16 09:36
Thanks @gjabouley-invn
I didn't know these were issues of SonarQube. I'll update as you suggested.

**Comment by mc1arke** [comment] 2024-08-11 14:48
Closing since plugins supporting [10.5](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.20.0) and [10.6](https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.21.0) have been released.

**Closed by mc1arke** 2024-08-11 14:48 UTC
