### ISSUE TITLE
Nullpointer when sonar.branch.name is missing

### ISSUE THREAD

**Issue by TorstenKruse** [mc1arke/sonarqube-community-branch-plugin#35] opened 2019-10-02 07:55 UTC
When calling mvn sonar:sonar on a project where sonar.branch.name is not set at all, a Nullpointer will occur.

I would expect to get the main branch analysed.

`[09:52:15] [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project xxx-maven-plugin: Unable to load component class org.sonar.scanner.scan.filesystem.InputComponentStore: Unable to load component interface org.sonar.scanner.scan.branch.BranchConfiguration: NullPointerException -> [Help 1]`

final Stacktrace:
`Caused by: java.lang.NullPointerException
        at com.github.mc1arke.sonarqube.plugin.scanner.CommunityBranchConfigurationLoader.computeBranchType(CommunityBranchConfigurationLoader.java:145)
        at com.github.mc1arke.sonarqube.plugin.scanner.CommunityBranchConfigurationLoader.createBranchConfiguration(CommunityBranchConfigurationLoader.java:128)
        at com.github.mc1arke.sonarqube.plugin.scanner.CommunityBranchConfigurationLoader.load(CommunityBranchConfigurationLoader.java:97)`

Sonar Qube 7.9.1 LTS
Branch Plugin 1.1.1

**Comment by mc1arke** [comment] 2019-10-02 08:26
Can you provide the full Maven command you're running? Presumably you've included `sonar.branch.target` or equivalent?

**Comment by TorstenKruse** [comment] 2019-10-02 08:50
The call is just "mvn sonar:sonar". But we have some magic in our parent pom which sets the sonar.branch.name if GIT_LOCAL_BRANCH is available.
But as this is not set in my local test environment there should be no sonar.branch.name at all.
The Nullpointer source line indicates that the branch is null, which matches this.

**Comment by mc1arke** [comment] 2019-10-02 09:29
You can only get to where the exception is being thrown if either `sonar.branch.target` or `sonar.branch.name` is set, due to the check in https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/064a24f0909e6841e30bf4797abd285cdfcb0655/src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java#L68 

I'll therefore need you to run maven in a more verbose mode to confirm what properties are actually being set when the build is executed.

Not setting `sonar.branch.name` when `sonar.branch.target` should probably throw an `IllegalStateException` since we can't confirm that the local branch is actually the same as the remote branch, although the `NullPointerException` at least defends against invalid data.

**Comment by TorstenKruse** [comment] 2019-10-02 09:54
Oh...well...we have in our parent pom an empty default for sonar.branch.target (<sonar.branch.target />) as sonarqube said "If left blank, this defaults to the master branch.".

If both are missing or empty, I would expect to get an analysis of the master branch.

**Comment by mc1arke** [comment] 2020-06-07 15:03
Closing this since the root cause has been explained and there doesn't seem to be any drive behind changing this.

**Closed by mc1arke** 2020-06-07 15:03 UTC
Labels: bug

**Comment by TorstenKruse** [comment] 2020-06-08 06:16
I think getting a Nullpointer is always a fault of the software and never of the user. So I expected to get a human readable error message at least, which tells the user, what he did wrong.
But it's not my project here...

**Comment by mc1arke** [comment] 2020-06-08 07:41
I would agree a `NullPointerException` isn't something a user should see as they should get a nice error message, but it was being driven by an invalid input and stopped processing so was a low priority fix. Given the version that supports 8.1 no longer supports `sonar.branch.target`, and this issue didn't get a lot of 'me too' comments/votes, I'm not proposing I try and fix it. I'm more than happy to support a PR if you do want to fix it though.
