### ISSUE TITLE
Unable to read plugin manifest from jar

### ISSUE THREAD

**Issue by ronnyfm** [mc1arke/sonarqube-community-branch-plugin#25] opened 2019-07-03 03:41 UTC
**Describe the bug**
SonarQube version: 7.9 LTS
Plugin version: 1.1.1

**To Reproduce**
1. Added the plugin
2. Start sonar using sonar.sh
3. Sonar is not able to start

Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /apps/tools/sonarqube-7.9/extensions/plugins/sonarqube-community-branch-plugin-1.1.1.jar
**Screenshots**

**Software Versions**
 - SonarQube Version: [e.g. Version 7.8 (build 26217)]
 - Plugin Version: [e.g. 1.1.0, or custom build from master at commit 004AD34FAA]

**Additional context**

**Comment by mc1arke** [comment] 2019-07-03 08:08
I've tried this locally using the latest plugin release and SonarQube 7.9 LTS and can start SonarQube with the plugin and scan branches without issue when using Open JDK 11 on Centos 7. Can you confirm:
1. What Operating System ('flavour' and version) you're running? I'm presuming a Linux distribution given your use of `sonar.sh` and and the path mentioned in the error
2. Is this a build of the plugin downloaded from the release page or have you performed your own build?
3. What version of Java are you using?
4. What are the permissions on the file plugin file, and do these allow access for the user that's starting SonarQube?

**Comment by ronnyfm** [comment] 2019-07-03 13:10
Thanks,

1. RHEL 7. 
2. This is the JAR from the Releases page, I did not perform my own build.
3. JDK 11.0.3
4. I am able to start sonar without the plugin.

**Comment by mc1arke** [comment] 2019-07-03 13:22
Is there more of a stacktrace than what you've copied into your original issue detail? I'd expect to see something similar to the following, which includes a `Caused By` stack indicating the original failure:

```
2019.07.03 14:14:55 ERROR web[][o.s.s.p.Platform] Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /home/mc1arke/scbp-issue25/sonarqube-7.9/extensions/plugins/sonarqube-community-branch-plugin-1.1.1.jar
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
	at org.sonar.core.platform.PluginInfo.create(PluginInfo.java:395)
	at org.sonar.server.plugins.ServerPluginRepository.loadPreInstalledPlugins(ServerPluginRepository.java:135)
	at org.sonar.server.plugins.ServerPluginRepository.start(ServerPluginRepository.java:103)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:113)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel2Container(Platform.java:177)
	at org.sonar.server.platform.Platform.init(Platform.java:87)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4817)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5283)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: /home/mc1arke/scbp-issue25/sonarqube-7.9/extensions/plugins/sonarqube-community-branch-plugin-1.1.1.jar (Permission denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
	... 27 common frames omitted
```

**Comment by mc1arke** [comment] 2019-07-10 06:45
Closing issues since no further information provided, and I'm unable to replicate the issue without specifically setting the permissions of the plugin file to a value that prevents the user running SonarQube from reading the plugin file.

**Closed by mc1arke** 2019-07-10 06:45 UTC
Labels: question
