### ISSUE TITLE
Difference between sonar issues number and annotations number in Bitbucket Server. 

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [mc1arke/sonarqube-community-branch-plugin#246] opened 2020-09-22 14:03 UTC
**Describe the bug**
Plugin creates annotations not for all sonar issues. Is it bug or expected behaviour?

**To Reproduce**
You have source file:
```
1: var a = 1 
2: var b = a+1
```
You create pull request and delete 2nd line. Sonar generates issue against 1st line: 'var a is defined but never used'. But plugin doesn't create annotation, I suppose because 1st line is not changed by PR. Is it correct?

**Expected behavior**
Same number of issues and annotations.

**Screenshots**
8 issues vs 7 annotations
![bitbucket](https://user-images.githubusercontent.com/19704782/93890394-f8856b80-fcf2-11ea-9567-99dc1836d4aa.png)

**Software Versions**
 - SonarQube Version: 8.0 (build 29455)
 - Plugin Version: 1.3.1
 - Bitbucket Server v6.5.3

**Comment by mc1arke** [comment] 2021-12-30 15:13
Yes, this is caused by Bitbucket not allowing annotations to be created on lines outside the diff. There's similar restrictions in other ALM tools which I've not managed to find a way of overcoming, and as a result I'm closing this issues as "Won't fix" given there isn't a reasonable fix that could be made here.

**Closed by mc1arke** 2021-12-30 15:13 UTC
Labels: bug
