### ISSUE TITLE
Sonarqube 8.3 support

### ISSUE THREAD

**Issue by mazmar** [mc1arke/sonarqube-community-branch-plugin#198] opened 2020-06-22 07:39 UTC
We are having troubles with sonarqube 8.2 and background task processing, namely: 
https://community.sonarsource.com/t/sonarqube-8-2-failed-background/21672
which is resolved in 8.3, SONAR-13262

any ETA on 8.3 being supported? anybody tried using branch sonarqube_82 with 8.3?

Thanks

**Comment by laoshancun** [comment] 2020-06-23 04:00
I am using branch  `sq-8_2-support` on Sonarqube `8.3.1`.

**Comment by jmecosta** [comment] 2020-06-30 12:39
@laoshancun how are u using 8.3.1? im getting this error with sonarqube_82 

```
2020.06.30 15:34:36 INFO  web[][o.s.s.q.ProjectsInWarningDaemon] Counting number of projects in warning will be disabled as there are no more projects in warning.
2020.06.30 15:36:59 ERROR web[AXMFOOMhiWRR/aIfAAAx][o.s.s.w.WebServiceEngine] Fail to process request http://localhost:9000/api/ce/submit?projectKey=ProjectKey%3AProjectName&projectName=ProjectName&characteristic=branch%3Dmaster&characteristic=branchType%3DBRANCH
java.lang.IllegalStateException: Current edition does not support branch feature
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:63)
	at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:83)
	at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:113)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:88)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:88)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by laoshancun** [comment] 2020-07-01 08:18
https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/sq-8_2-support#installation

> Either build the project or download a compatible release version of the plugin JAR. Copy the plugin JAR file to the extensions/plugins/ and the lib/common/ directories of your SonarQube instance and restart SonarQube

**Comment by jmecosta** [comment] 2020-07-01 11:38
@laoshancun yeah that was my first guess, but it doesnt work!  should have put the installed plugins sorry about that:

```
14:38:13.291 DEBUG: Plugins:
14:38:13.291 DEBUG:   * C++ (Community) 2.0.0.2037 (cxx)
14:38:13.291 DEBUG:   * SonarPython 2.8.0.6204 (python)
14:38:13.291 DEBUG:   * SonarCSS 1.2.0.1325 (cssfamily)
14:38:13.292 DEBUG:   * MSBuild 1.5.7 (sonarqubemsbuildplugin)
14:38:13.292 DEBUG:   * JaCoCo 1.1.0.898 (jacoco)
14:38:13.292 DEBUG:   * Sonar Community F# 3.1.371 (communityfsharp)
14:38:13.292 DEBUG:   * SonarGo 1.6.0.719 (go)
14:38:13.292 DEBUG:   * SonarKotlin 1.5.0.315 (kotlin)
14:38:13.293 DEBUG:   * Svn 1.9.0.1295 (scmsvn)
14:38:13.293 DEBUG:   * SonarJS 6.2.0.12043 (javascript)
14:38:13.293 DEBUG:   * SonarRuby 1.5.0.315 (ruby)
14:38:13.293 DEBUG:   * SonarScala 1.5.0.315 (sonarscala)
14:38:13.293 DEBUG:   * C# Code Quality and Security 8.6.1.17183 (csharp)
14:38:13.294 DEBUG:   * Java Code Quality and Security 6.3.0.21585 (java)
14:38:13.294 DEBUG:   * SonarHTML 3.2.0.2082 (web)
14:38:13.294 DEBUG:   * Git 1.11.1.2008 (scmgit)
14:38:13.294 DEBUG:   * SonarFlex 2.5.1.1831 (flex)
14:38:13.294 DEBUG:   * SonarXML 2.0.1.2020 (xml)
14:38:13.294 DEBUG:   * SonarPHP 3.3.0.5166 (php)
14:38:13.295 DEBUG:   * SonarTS 2.1.0.4359 (typescript)
14:38:13.295 DEBUG:   * VB.NET Code Quality and Security 8.6.1.17183 (vbnet)
14:38:13.295 DEBUG:   * Community Branch Plugin 1.3.2-SNAPSHOT (communityBranchPlugin)
```

**Comment by laoshancun** [comment] 2020-07-07 08:20
Maybe you should build your own image.
```Dockerfile
ARG VERSION=8.3.1
FROM sonarqube:${VERSION}-community

COPY *.jar /opt/sonarqube/lib/common/

RUN chmod 644 -R /opt/sonarqube/lib/common/* \
    && chown sonarqube:sonarqube -R /opt/sonarqube/lib/common/*
```

**Comment by jmecosta** [comment] 2020-07-07 13:42
@laoshancun why? the plugin should work on top of the vanilla version no? https://www.sonarqube.org/success-download-community-edition/

**Comment by jessesomerville** [comment] 2020-07-07 19:58
I am having the same issue.  After creating my GitHub app and enabling the ALM Integration, it still says that I have to activate the PR Decorator in the global settings when I go to Project Settings > General Settings > Pull Request Decorator.  This is also in my logs:

```
2020.07.07 17:47:21 DEBUG ce[AXMqY6E7vtnl55V4b9sx][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] found 3 pull request decorators
2020.07.07 17:47:21 DEBUG ce[AXMqY6E7vtnl55V4b9sx][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] No ALM has been set on the current project
2020.07.07 17:47:21 INFO  ce[AXMqY6E7vtnl55V4b9sx][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=SUCCESS | time=1ms
```

**Comment by laoshancun** [comment] 2020-07-08 08:20
![image](https://user-images.githubusercontent.com/4952748/86895033-7abfb400-c136-11ea-8680-18a63359b598.png)
tested on 7.3.1.

**Comment by jmecosta** [comment] 2020-07-08 08:49
@laoshancun 7.3.1? what is that? the version on this branch is sonarqube-community-branch-plugin-1.3.2-SNAPSHOT

**Comment by mazmar** [comment] 2020-07-08 09:12
I think he meant SQ 8.3.1. It is working for me also.

**Comment by jessesomerville** [comment] 2020-07-08 13:17
Yeah I have double checked all of that, unfortunately.
```
$ ls -l $SONARQUBE_HOME/lib/common/
total 74680
-rw-r--r-- 1 root sonarqube    62983 May  7 13:24 activation-1.1.jar
...
...
-rw-r--r-- 1 root sonarqube  5092023 Jul  7 03:44 sonarqube-community-branch-plugin-1.3.2.jar
-rw-r--r-- 1 root sonarqube   479939 May  7 13:25 sonar-scanner-protocol-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube   659725 May  7 13:25 sonar-server-common-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube    57747 May  7 13:24 sonar-update-center-common-1.23.0.723.jar
-rw-r--r-- 1 root sonarqube    79527 May  7 13:25 sonar-webserver-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube    88390 May  7 13:25 sonar-webserver-api-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube   241883 May  7 13:25 sonar-webserver-auth-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube   178199 May  7 13:25 sonar-webserver-core-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube   122861 May  7 13:25 sonar-webserver-es-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube  1980185 May  7 13:25 sonar-webserver-webapi-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube    27436 May  7 13:25 sonar-webserver-ws-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube  4052666 May  7 13:25 sonar-ws-8.3.1.34397.jar
-rw-r--r-- 1 root sonarqube   161867 May  7 13:24 stax2-api-3.1.4.jar
-rw-r--r-- 1 root sonarqube    78629 May  7 13:24 staxmate-2.0.1.jar
-rw-r--r-- 1 root sonarqube    51208 May  7 13:24 t-digest-3.2.jar
-rw-r--r-- 1 root sonarqube    12373 May  7 13:24 tomcat-annotations-api-8.5.53.jar
-rw-r--r-- 1 root sonarqube  3249552 May  7 13:24 tomcat-embed-core-8.5.53.jar
-rw-r--r-- 1 root sonarqube     7563 May  7 13:24 transport-6.8.4.jar
-rw-r--r-- 1 root sonarqube    81905 May  7 13:24 transport-netty4-client-6.8.4.jar
-rw-r--r-- 1 root sonarqube   512742 May  7 13:24 woodstox-core-5.0.3.jar
-rw-r--r-- 1 root sonarqube   491270 May  7 13:24 woodstox-core-lgpl-4.4.1.jar
-rw-r--r-- 1 root sonarqube  1129826 May  7 13:24 xmlsec-2.1.4.jar
```

```
$ ls -l $SONARQUBE_HOME/extensions/plugins/
total 107804
-rwxrwxr-x 1 root sonarqube      224 May  7 13:22 README.txt
-rwxrwxr-x 1 root sonarqube  5026371 May 11 10:13 sonar-csharp-plugin-8.7.0.17535.jar
-rwxrwxr-x 1 root sonarqube  8787134 May  7 13:31 sonar-css-plugin-1.2.0.1325.jar
-rwxrwxr-x 1 root sonarqube  1544789 May  7 13:31 sonar-flex-plugin-2.5.1.1831.jar
-rwxrwxr-x 1 root sonarqube  6857471 May  7 13:31 sonar-go-plugin-1.6.0.719.jar
-rwxrwxr-x 1 root sonarqube   807419 May  7 13:31 sonar-html-plugin-3.2.0.2082.jar
-rwxrwxr-x 1 root sonarqube    19648 May  7 13:31 sonar-jacoco-plugin-1.1.0.898.jar
-rwxrwxr-x 1 root sonarqube 18781589 May 14 13:25 sonar-java-plugin-6.4.0.21967.jar
-rwxrwxr-x 1 root sonarqube 10073594 Apr  3 13:36 sonar-javascript-plugin-6.2.1.12157.jar
-rwxrwxr-x 1 root sonarqube  7595999 May  7 13:31 sonar-kotlin-plugin-1.5.0.315.jar
-rwxrwxr-x 1 root sonarqube  5148726 May 28 10:11 sonar-php-plugin-3.5.0.5655.jar
-rwxrwxr-x 1 root sonarqube  4339897 May 26 10:12 sonar-python-plugin-2.11.0.6843.jar
-rwxrwxr-x 1 root sonarqube  5092023 Jul  7 03:43 sonarqube-community-branch-plugin-1.3.2.jar
-rwxrwxr-x 1 root sonarqube 10036210 May  7 13:31 sonar-ruby-plugin-1.5.0.315.jar
-rwxrwxr-x 1 root sonarqube  9202024 May  7 13:31 sonar-scala-plugin-1.5.0.315.jar
-rwxrwxr-x 1 root sonarqube  3800973 May  7 13:31 sonar-scm-git-plugin-1.11.1.2008.jar
-rwxrwxr-x 1 root sonarqube  7229293 May  7 13:31 sonar-scm-svn-plugin-1.9.0.1295.jar
-rwxrwxr-x 1 root sonarqube     5746 Nov 18  2019 sonar-typescript-plugin-2.1.0.4362.jar
-rwxrwxr-x 1 root sonarqube  3749162 May  7 13:31 sonar-vbnet-plugin-8.6.1.17183.jar
-rwxrwxr-x 1 root sonarqube  2242738 May  7 13:31 sonar-xml-plugin-2.0.1.2020.jar
```

I have tried both building the `sq-8_2-support` branch and using the "1.4.0" release which is just the 1.3.2 jar.  Both gave me the same results.

**Comment by jmecosta** [comment] 2020-07-08 17:46
Hum. @mazmar what u mean lib/common?  Thats not how plugins are installed

What are the analyses arguments u are using? Pull request or branch? I
suspect pull request it may be working but not branch

**Comment by nixel2007** [comment] 2020-07-08 18:20
> Thats not how plugins are installed

this plugin needs to be installed in extension/plugins and lib/common

**Comment by jmecosta** [comment] 2020-07-08 19:57
Ok, i see its in the readme. Thanks for pointing it out

**Comment by mc1arke** [comment] 2020-07-15 13:18
To confirm: the 8.2 branch should work with 8.3. I'm therefore closing this issue since it's not actually a bug.

**Closed by mc1arke** 2020-07-15 13:18 UTC
Labels: bug

**Comment by jmecosta** [comment] 2020-07-22 08:41
confirmed! thanks for the help
