### ISSUE TITLE
[Bitbucket] DevOps Platform Integration check failing

### ISSUE THREAD

**Issue by Martijn-W** [mc1arke/sonarqube-community-branch-plugin#591] opened 2022-04-21 14:37 UTC
**Describe the bug**
SonarQube gives an error when trying to enable PR decoration for Bitbucket Cloud projects.
Error:
![image](https://user-images.githubusercontent.com/52448740/164481561-3dcdf62e-a434-4ead-a8a1-d5d2e79b1d48.png)

Under Administration -> DevOps Platform Integrations -> Bitbucket it shows that the configuration is valid:
![image](https://user-images.githubusercontent.com/52448740/164481814-cb069bfa-801b-445c-9ccd-3d48be8d61ca.png)

I double checked the OAuth and app password permissions to include read access to 'Repositories' and 'Pull Requests'.

**To Reproduce**
1. Go to a Bitbucket Cloud project
2. Navigate to Project Settings -> DevOps Platform Integration
3. Provide a valid configuration and repository slug
4. Click 'Save'
5. Click 'Check Configuration'

**Expected behavior**
Success message

**Software Versions**
 - SonarQube Version: 9.4.0.54424
 - Plugin Version: 1.11.0

**Comment by luqq** [comment] 2022-05-10 09:12
PR #586 will probably fix it but it will break compatibility for SQ versions <=9.3

**Comment by mc1arke** [comment] 2022-06-20 08:13
Duplicate of #585

**Closed by mc1arke** 2022-06-20 08:13 UTC
Labels: bug, duplicate
