### ISSUE TITLE
Feature branches new code period is getting set to unexpected old dates compared to reference branch

### ISSUE THREAD

**Issue by Wankhadess** [mc1arke/sonarqube-community-branch-plugin#506] opened 2021-12-08 12:44 UTC
**Describe the bug**
In one of our projects whenever we scan any feature branches it's **New Code** always points to older date of creation when **compared to reference branch(develop)**. The New Code period for the project is set to point its reference branch(develop).

Even when the feature branch is newly created today it ends up mentioned as old date, and brings issues with it.

**Note:** Also, There is no activity present on that date in SonarQube which is strange.

**To Reproduce**
1. Create SonarQube Branches master[main branch] , develop ,feature(derived from develop).
<img width="289" alt="branches" src="https://user-images.githubusercontent.com/64198883/145205938-6a41a835-d9d2-4fd3-b4c7-6037f782d0e7.PNG">

2. Change the New Code period Setting **At Project Level** to Reference Branch(develop) and At develop set it to Specific Analysis see the below settings.
<img width="718" alt="projectsetting" src="https://user-images.githubusercontent.com/64198883/145206669-c7df874f-db04-4638-8c74-baf8652e2a62.PNG">

3. After above changes analysis the feature branch(develop_test) / create new branch see the below new code diff
<img width="343" alt="devetest" src="https://user-images.githubusercontent.com/64198883/145207543-3c983b29-2493-4799-9078-35ba7029c980.png">
 develop_test is a new branch created on 7-12-2021

See the last Analysis on develop branch below 
<img width="745" alt="developb" src="https://user-images.githubusercontent.com/64198883/145208659-db7c3c20-4ad8-43b0-b32d-ff01a1691af9.PNG">

**Issues and It's Expected behavior**
1. As per the New Code definition https://docs.sonarqube.org/latest/project-administration/new-code-period/ The New Code compare date should point to 2 Dec not 4 Nov.
2. There is No Activity listed in SonarQube on 4 Nov to compare, see the below Activity SS
<img width="241" alt="avtivity" src="https://user-images.githubusercontent.com/64198883/145209401-c24b24d9-9c25-464b-8bff-101a0231ea71.PNG">

**Software Versions**
 - SonarQube Version: LTS Version 8.9.2 (build 46101)
 - Plugin Version: Community Branch Plugin Version 1.8.1

**Comment by Wankhadess** [comment] 2021-12-14 07:48
Hi , Any update on this????

**Comment by mc1arke** [comment] 2021-12-14 14:19
Is this a duplicate of #449 ?

**Comment by Wankhadess** [comment] 2021-12-15 06:46
mc1arke No it's the different use case. At branch Level the New Code compare date and new code analysis is not generating as expected. please see the above Use case scenario for reference.

**Comment by mc1arke** [comment] 2021-12-30 14:20
I've not attempted to follow your replication steps yet, but can you confirm what `develop_test` looks like, specifically what date the commit was created that if the last common commit between `develop_test` and `develop`?

**Comment by Wankhadess** [comment] 2022-01-06 07:17
develop_test is a new branch created on 7-12-2021 from develop. 
Some changes has been done on develop_test on same day.

**Comment by Wankhadess** [comment] 2022-02-25 06:05
@mc1arke Hi Any update on this???

**Comment by mc1arke** [comment] 2022-04-05 18:24
Can you confirm if this can still be replicated with Sonarqube 9.3 please?

**Closed** 2022-04-28 12:57 UTC
Labels: bug, question
